#:schema node_modules/wrangler/config-schema.json
name = "dynamic-imports-io-repro"
main = "src/index.js"
compatibility_date = "2024-07-25"
compatibility_flags = ["nodejs_compat"]

rules = [
  { type = "ESModule", globs = ["**/*.js"], fallthrough = true }
]
